name: Dependabot Enable auto-merge

on:
  pull_request:
    branches: [ main ]

permissions: { }

jobs:

  ApproveDependabotPr:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET 10.0.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: ApproveDependabotPr
        id: ApproveDependabotPr
        run: dotnet run --project _atom/_atom.csproj -- ApproveDependabotPr --skip --headless
        env:
          pull-request-number: ${{ github.event.number }}

